"""agregar columna descripcion a tareas

Revision ID: 3dcf5e7ddd56
Revises: 19a63bab5108
Create Date: 2026-06-22 23:32:59.267323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dcf5e7ddd56'
down_revision: Union[str, None] = '19a63bab5108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
